### ISSUE TITLE
Don't open a new tab for URL hash properties of the current page

### ISSUE THREAD

**Issue by deadcombo** [cssnr/open-links-in-new-tab#27]
Hi.

Links such as https://wiki.archlinux.org/title/Systemd#Drop-in_files trigger a new tab at the moment. 
While that can be a desired behavior for complex pages it would be nice to have the option to not have a new tab when following # links.
Ideally stored per-site.

Thanks! This add-on makes web-browsing a lot more consistent.

**Comment by smashedr** [comment]
That is a solid request. I will at minimum add a global option, and hopefully get a per-site option.

**Comment by smashedr** [comment]
I had a few pending updates, I released them and the global option for Anchor Links in 0.2.1.
By default, anchor links for the same origin are disabled and can be enabled in the Popup or Options.

The core logic for the feature is as follows:
```javascript
if (!options.anchorLinks && element.href.includes('#')) {
    const url = new URL(element.href)
    if (url.origin === window.location.origin) {
        continue // do not update this link
    }
}
```

Firefox publishing is almost always instant and available now. Google Chrome is pending review, but a signed release is always available form the latest release in the form of a `.crx` download from: https://github.com/cssnr/open-links-in-new-tab/releases/tag/0.2.1

There are a few pressing issues I need to resolve before implementing per-site options; therefore, I put it on the roadmap.

Thank you for reporting this issue as it was - not to sound like ChatGPT - an oversight on my part.
